Gymbokning/Controllers/GymClassesController.cs
using AutoMapper;
using Booking.Core.Entities;
using Booking.Core.Repositories;
using Booking.Core.ViewModels;
using Booking.Data.Data;
using Booking.Web.Extensions;
using Booking.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;


namespace Booking.Web.Controllers
{
    public class GymClassesController : Controller
    {
        //private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _uow;
        private readonly IMapper _mapper;

        public GymClassesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IUnitOfWork unitOfWork, IMapper mapper)
        {
            //_context = context;
            _userManager = userManager;
            _uow = unitOfWork;
            _mapper = mapper;

        }

        // GET: GymClasses
        [AllowAnonymous]
        public async Task<IActionResult> Index(IndexViewModel viewModel)
        {
            if (User.Identity != null && !User.Identity.IsAuthenticated)
                return View(_mapper.Map<IndexViewModel>(await _uow.GymClassRepository.GetAsync()));

            var gymClasses = viewModel.ShowHistory ?
                await _uow.GymClassRepository.GetHistoryAsync()
                :
                await _uow.GymClassRepository.GetWithAttendingAsync()
                ;

            return View(_mapper.Map<IndexViewModel>(gymClasses));
        }

        // GET: GymClasses/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            return View(await _uow.GymClassRepository.GetWithAttendingAsync((int)id!));
        }


        // GET: GymClasses/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return Request.IsAjax() ? PartialView("CreateGymClassPartial") : View();
        }

        // POST: GymClasses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(GymClass gymClass)
        {
            if (ModelState.IsValid)
            {
                _uow.GymClassRepository.Add(gymClass);
                await _uow.CompleteAsync();
                return Request.IsAjax() ?
                    PartialView("GymClassPartial", _mapper.Map<GymClassViewModel>(gymClass)) :
                    RedirectToAction(nameof(Index));
            }
            if (Request.IsAjax())
            {
                Response.StatusCode = StatusCodes.Status400BadRequest;
                return PartialView("CreateGymClassPartial", gymClass);
            }
            return View(gymClass);
        }


        // GET: GymClasses/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            return View(await _uow.GymClassRepository.GetAsync((int)id!));
        }


        // POST: GymClasses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, GymClass gymClass)
        {
            if (id != gymClass.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _uow.GymClassRepository.Update(gymClass);
                    await _uow.CompleteAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GymClassExists(gymClass.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gymClass);
        }


        // GET: GymClasses/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            return View(await _uow.GymClassRepository.GetAsync((int)id!));
        }

        // POST: GymClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gymClass = await _uow.GymClassRepository.GetAsync(id);
            if (gymClass != null)
            {
                _uow.GymClassRepository.Remove(gymClass);
            }

            await _uow.CompleteAsync();
            return RedirectToAction(nameof(Index));
        }


        [Authorize]
        public async Task<IActionResult> BookingToggle(int? id)
        {
            if (id == null) return NotFound();

            //get the gymclass with attendees
            var gymClass = await _uow.GymClassRepository.GetWithAttendingAsync((int)id!);

            if (gymClass == null)
            {
                return NotFound();
            }

            //get user id from user manager
            var userId = _userManager.GetUserId(User);
            if (userId == null) { return BadRequest(); }


            var attending = await _uow.ApplicationUserGymClassRepository.FindAsync(userId, (int)id!);

            if (attending == null)
            {
                var applicationUserGymClass = new ApplicationUserGymClass
                {
                    ApplicationUserId = userId,
                    GymClassId = id.GetValueOrDefault(),
                };

                _uow.ApplicationUserGymClassRepository.Add(applicationUserGymClass);
                await _uow.CompleteAsync();

            }
            else
            {
                _uow.ApplicationUserGymClassRepository.Remove(attending);
                await _uow.CompleteAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool GymClassExists(int id)
        {
            return (_uow.GymClassRepository.Exists(id));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Gymbokning/Controllers/UsersController.cs
using Booking.Core.Entities;
using Booking.Data.Data;
using Booking.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Booking.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UsersController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;

        }
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.GetUsersInRoleAsync("Member");

            return users != null ?
                          View(users) :
                          Problem("Users with Member Role is null.");
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var model = await _userManager.FindByIdAsync(id);
            return View(model);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            throw new NotImplementedException();
        }


        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ApplicationUser user)
        {
            throw new NotImplementedException();
        }


        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            var model = await _userManager.FindByIdAsync(id);
            return View(model);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var member = await _userManager.FindByIdAsync(id);
            if (member != null)
            {
                await _userManager.DeleteAsync(member);
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

Gymbokning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gymbokning</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Gymbokning.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark text-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="GymClasses" asp-action="Index">Gymbokning</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="GymClasses" asp-action="Index">Classes</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index">Members</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Gymbokning - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Identity/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/Identity/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>